[package]
name = "smiscc"
version = "0.1.0"
edition = "2024"

[dependencies]
colorize = "0.1.0"
strum = "0.27.2"
strum_macros = "0.27.2"
termimad = "0.34.0"
uuid = { version = "1.18.1", features = [ "v4" ] }
